// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"github.com/cjstarcc/zeroframework/user/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CSLoginResp = user.CSLoginResp
	SCLoginReq  = user.SCLoginReq

	User interface {
		Login(ctx context.Context, in *SCLoginReq, opts ...grpc.CallOption) (*CSLoginResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *SCLoginReq, opts ...grpc.CallOption) (*CSLoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
